In [1]:
import numpy as np


In [11]:

# Example list of 1*3 numpy arrays
arr_list = [np.array([14.500000,19.300000,22.700000]), 
            np.array([10.500000,16.700000,20.100000]), 
            np.array([11.300000,14.300000,22.400000]),
            np.array([14.500000,19.300000,22.700000]), 
            np.array([10.500000,16.700000,44.100000]), 
            np.array([11.300000,14.300000,44.400000]), 
            np.array([10.900000,19.200000,44.100000])]

# Calculate the z-score of each array
z_scores = np.abs((arr_list - np.mean(arr_list, axis=0)) / np.std(arr_list))
print(z_scores)
# Remove arrays with a z-score greater than 3
arr_list = [arr_list[i] for i in range(len(arr_list)) if np.max(z_scores[i]) < 3]
print(arr_list)

[[0.24358833 0.20705008 0.83361339]
 [0.13532685 0.03924479 1.07990826]
 [0.05954381 0.26659389 0.86203203]
 [0.24358833 0.20705008 0.83361339]
 [0.13532685 0.03924479 1.19358281]
 [0.05954381 0.26659389 1.22200145]
 [0.09743533 0.1975772  1.19358281]]
[array([14.5, 19.3, 22.7]), array([10.5, 16.7, 20.1]), array([11.3, 14.3, 22.4]), array([14.5, 19.3, 22.7]), array([10.5, 16.7, 44.1]), array([11.3, 14.3, 44.4]), array([10.9, 19.2, 44.1])]


In [9]:
np.mean(arr_list, axis=0)

array([12.1       , 16.76666667, 21.73333333])